// Scaffold templates for `fugue new` (C3). Pure string builders — no I/O.
//
// Every template is a parameterized copy of a lint-tested golden example
// (`docs/examples/01-04`, `08`, `09`), so the generated `dag.ts` is compliant
// by construction: current model ids, `frameworkError.*` (never raw `err`
// literals), correct fan-in schemas keyed by source-node id, bucketed
// confidence via the spread-override pattern, and `$input` edges for the
// request. `new.test.ts` lints every (shape × llm) combination to keep that
// promise honest — a template that stops linting fails the build.

import { match } from "ts-pattern";
import { DAG_SHAPES } from "../types/dag.js";

/**
 * The topologies `fugue new --shape` can scaffold — one per DAG shape. Sourced
 * from the canonical `DAG_SHAPES` tuple so it cannot drift from `DagProvenance`.
 */
export const SHAPES = DAG_SHAPES;
export type Shape = (typeof SHAPES)[number];

export interface TemplateCtx {
  /** DAG id / directory name (kebab-case). */
  readonly name: string;
  /** Owning team (from the `<team>/<name>` path). */
  readonly team: string;
  /** PascalCase of `name`, for the factory identifier (`create<Pascal>Dag`). */
  readonly pascal: string;
  /** Whether to scaffold an LLM node + prompt. */
  readonly llm: boolean;
  /**
   * Whether to add a human-review gate (ADR-0060) — a `createHumanReviewNode`
   * that pauses the run for an approve/reject decision before it completes.
   * Optional so existing call sites that predate the flag stay valid; only the
   * `linear` shape reads it (the CLI rejects `--review` with other shapes).
   */
  readonly review?: boolean;
}

/** A prompt file to emit alongside an `--llm` scaffold. */
export interface PromptFile {
  /** Prompt name (registry key + `<name>.txt`). */
  readonly name: string;
  /** Template body, with `{{placeholder}}` vars matching the node's buildInput. */
  readonly body: string;
}

export interface Scaffold {
  readonly dagTs: string;
  /** Present only for `--llm` scaffolds. */
  readonly prompt?: PromptFile;
}

// A current model id — kept in one place so a model-id bump touches one line.
// See `@fuguejs/framework/docs/llm-dag-authoring.md` ("Model ids").
const DEFAULT_MODEL = "claude-sonnet-4-6";

/** Shared `frameworkError.*` confidence/spread-override boilerplate for LLM nodes. */
const llmConfidenceReturn = `  // createLlmNode defaults \`confidence: { mode: "none" }\`. Spread-override the
  // field to emit the model's self-reported BUCKET through the framework's
  // typed confidence channel — never a number (see docs/llm-dag-authoring.md).
  return {
    ...node,
    confidence: {
      mode: "value",
      extract: (o) => confidence(o.confidence, "self-reported-bucket"),
    },
  };`;

const registration = (ctx: TemplateCtx, dagExpr: string, description: string): string =>
  `const registration: DagRegistration = {
  dag: ${dagExpr},
  inputSchema: InputSchema,
  route: "/${ctx.name}",
  meta: {
    description: ${JSON.stringify(description)},
    version: "1.0.0",
  },
};

export default registration;
`;

// ---------------------------------------------------------------------------
// linear — A → B (defineLinearDag)
// ---------------------------------------------------------------------------

const linear = (ctx: TemplateCtx): Scaffold => {
  if (!ctx.llm) {
    // Optional human-review gate (ADR-0060). `createHumanReviewNode` is a typed
    // passthrough: the run SUSPENDS after it and awaits a decision before the DAG
    // completes. The reviewer sees `summarize`'s output.
    const reviewBlock = ctx.review
      ? `
// Human-review gate: the run SUSPENDS after \`summarize\` and waits for a decision
// (approve / reject / approve-with-edit / reroute) before the DAG completes.
const review = createHumanReviewNode({
  id: "review",
  schema: ResultSchema,
  prompt: "Approve this result before it is returned?",
});
`
      : "";
    const dagTs = `// ${ctx.name} — linear pipeline (fetch → transform${ctx.review ? " → human review" : ""}) via \`defineLinearDag\`.
//
// The simplest topology: each node feeds the next, edges inferred from array
// order, the last node is the output. Generated by \`fugue new\`; fill in the
// real schemas, fetch, and transform.

import { z } from "zod";
import {
  createFetchNode,
${ctx.review ? "  createHumanReviewNode,\n" : ""}  createTransformNode,
  defineLinearDag,
  err,
  frameworkError,
  ok,
} from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

const InputSchema = z.object({ id: z.string() });
const RecordSchema = z.object({ id: z.string(), value: z.number() });
const ResultSchema = z.object({ summary: z.string() });

const fetchRecord = createFetchNode({
  id: "fetch-record",
  inputSchema: InputSchema,
  outputSchema: RecordSchema,
  fetch: async (input) => ok({ id: input.id, value: 42 }),
});

const summarize = createTransformNode({
  id: "summarize",
  inputSchema: RecordSchema,
  outputSchema: ResultSchema,
  transform: (record) =>
    record.value < 0
      ? err(frameworkError.validation("summarize", "value must be non-negative", "value"))
      : ok({ summary: \`Record \${record.id}: \${record.value}\` }),
});
${reviewBlock}
const dag = defineLinearDag({
  id: "${ctx.name}",
  nodes: [fetchRecord, summarize${ctx.review ? ", review" : ""}],
});

${registration(ctx, "dag", `Linear pipeline scaffold for ${ctx.name}. Replace the placeholder fetch + transform.`)}`;
    return { dagTs };
  }

  // Optional human-review gate over the LLM output — the canonical "approve the
  // AI draft before it ships" pattern.
  const reviewBlock = ctx.review
    ? `
// Human-review gate: the run SUSPENDS after the LLM node and waits for a decision
// (approve / reject / approve-with-edit / reroute) before the DAG completes.
const review = createHumanReviewNode({
  id: "review",
  schema: SummarySchema,
  prompt: "Approve this summary before it is returned?",
});
`
    : "";
  const dagTs = `// ${ctx.name} — linear pipeline ending in an LLM node${ctx.review ? " + a human-review gate" : ""}, built as a
// FACTORY so the model seam is injectable (production calls \`create${ctx.pascal}Dag()\`;
// a test passes a fake model id + FakeLlmClient). Generated by \`fugue new --llm\`.

import { z } from "zod";
import {
  confidence,
  createFetchNode,
${ctx.review ? "  createHumanReviewNode,\n" : ""}  createLlmNode,
  defineLinearDag,
  ok,
} from "@fuguejs/framework";
import type { LlmNodeDef } from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

export interface ${ctx.pascal}DagOpts {
  /** Model seam; defaults to a current id. Tests pass a fake id + FakeLlmClient. */
  readonly model?: string;
}

const DEFAULT_MODEL = "${DEFAULT_MODEL}";

const InputSchema = z.object({ id: z.string() });
const RecordSchema = z.object({ id: z.string(), text: z.string() });
// Confidence comes back as a BUCKET, never a number — the prompt forbids digits.
const SummarySchema = z.object({
  summary: z.string(),
  confidence: z.enum(["high", "medium", "low"]),
});

const fetchRecord = createFetchNode({
  id: "fetch-record",
  inputSchema: InputSchema,
  outputSchema: RecordSchema,
  fetch: async (input) => ok({ id: input.id, text: "lorem ipsum" }),
});

const createSummarize = (
  model: string,
): LlmNodeDef<z.infer<typeof RecordSchema>, z.infer<typeof SummarySchema>> => {
  const node = createLlmNode({
    id: "summarize",
    inputSchema: RecordSchema,
    outputSchema: SummarySchema,
    promptName: "${ctx.name}",
    model,
    buildInput: (record) => ({ text: record.text }),
  });
${llmConfidenceReturn}
};
${reviewBlock}
export const create${ctx.pascal}Dag = (opts: ${ctx.pascal}DagOpts = {}) =>
  defineLinearDag({
    id: "${ctx.name}",
    nodes: [fetchRecord, createSummarize(opts.model ?? DEFAULT_MODEL)${ctx.review ? ", review" : ""}],
  });

${registration(ctx, `create${ctx.pascal}Dag()`, `Linear LLM pipeline scaffold for ${ctx.name}. Fetch a record, then summarize it.`)}`;

  return {
    dagTs,
    prompt: {
      name: ctx.name,
      body: `You summarize records concisely.

Summarize the following text in one sentence:

{{text}}

Respond as JSON: { "summary": string, "confidence": "high" | "medium" | "low" }.
Set confidence by how much signal the text carries — never use a number.
`,
    },
  };
};

// ---------------------------------------------------------------------------
// fan-out / diamond — source → [branch…] → join
// ---------------------------------------------------------------------------

const fanShape = (ctx: TemplateCtx, helper: "defineFanOut" | "defineDiamond"): Scaffold => {
  const kind = helper === "defineDiamond" ? "diamond" : "fan-out";
  const joinNote =
    helper === "defineDiamond"
      ? "the join is REQUIRED — the topology always reconverges"
      : "an optional join fans the branches back in";

  if (!ctx.llm) {
    const dagTs = `// ${ctx.name} — ${kind} (source → parallel branches → join) via \`${helper}\`.
//
// One source feeds N branches that run concurrently; ${joinNote}. The join
// receives a fan-in object keyed by each branch's node id. Generated by
// \`fugue new\`.

import { z } from "zod";
import {
  ${helper},
  createFetchNode,
  createTransformNode,
  ok,
} from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

const InputSchema = z.object({ id: z.string() });
const TriggerSchema = z.object({ id: z.string() });
const ASchema = z.object({ a: z.string() });
const BSchema = z.object({ b: z.number() });

const trigger = createFetchNode({
  id: "trigger",
  inputSchema: InputSchema,
  outputSchema: TriggerSchema,
  fetch: async (input) => ok({ id: input.id }),
});

const fetchA = createFetchNode({
  id: "fetch-a",
  inputSchema: TriggerSchema,
  outputSchema: ASchema,
  fetch: async () => ok({ a: "alpha" }),
});

const fetchB = createFetchNode({
  id: "fetch-b",
  inputSchema: TriggerSchema,
  outputSchema: BSchema,
  fetch: async () => ok({ b: 1 }),
});

// The join sees both branches keyed by their node ids — keys MUST equal the
// incoming set (\`fugue lint\` enforces this).
const FanInSchema = z.object({
  "fetch-a": ASchema,
  "fetch-b": BSchema,
});
const MergedSchema = z.object({ a: z.string(), b: z.number() });

const merge = createTransformNode({
  id: "merge",
  inputSchema: FanInSchema,
  outputSchema: MergedSchema,
  transform: (fanIn) => ok({ a: fanIn["fetch-a"].a, b: fanIn["fetch-b"].b }),
});

const dag = ${helper}({
  id: "${ctx.name}",
  source: trigger,
  branches: [fetchA, fetchB],
  join: merge,
});

${registration(ctx, "dag", `${kind} scaffold for ${ctx.name}: one source, two parallel branches, a keyed join.`)}`;
    return { dagTs };
  }

  const dagTs = `// ${ctx.name} — ${kind} with an LLM branch, built as a FACTORY so the model
// seam is injectable. One branch calls the model; ${joinNote}. Generated by
// \`fugue new --llm\`.

import { z } from "zod";
import {
  ${helper},
  confidence,
  createFetchNode,
  createLlmNode,
  createTransformNode,
  ok,
} from "@fuguejs/framework";
import type { LlmNodeDef } from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

export interface ${ctx.pascal}DagOpts {
  /** Model seam; defaults to a current id. Tests pass a fake id + FakeLlmClient. */
  readonly model?: string;
}

const DEFAULT_MODEL = "${DEFAULT_MODEL}";

const InputSchema = z.object({ id: z.string() });
const TriggerSchema = z.object({ id: z.string(), label: z.string() });
const AnalysisSchema = z.object({
  analysis: z.string(),
  confidence: z.enum(["high", "medium", "low"]),
});
const BSchema = z.object({ b: z.number() });

const trigger = createFetchNode({
  id: "trigger",
  inputSchema: InputSchema,
  outputSchema: TriggerSchema,
  fetch: async (input) => ok({ id: input.id, label: "lead" }),
});

const createAnalyze = (
  model: string,
): LlmNodeDef<z.infer<typeof TriggerSchema>, z.infer<typeof AnalysisSchema>> => {
  const node = createLlmNode({
    id: "analyze",
    inputSchema: TriggerSchema,
    outputSchema: AnalysisSchema,
    promptName: "${ctx.name}",
    model,
    buildInput: (trig) => ({ label: trig.label }),
  });
${llmConfidenceReturn}
};

const fetchB = createFetchNode({
  id: "fetch-b",
  inputSchema: TriggerSchema,
  outputSchema: BSchema,
  fetch: async () => ok({ b: 1 }),
});

// Fan-in keyed by the two branch node ids — \`fugue lint\` checks the key set.
const FanInSchema = z.object({
  analyze: AnalysisSchema,
  "fetch-b": BSchema,
});
const MergedSchema = z.object({ analysis: z.string(), b: z.number() });

const merge = createTransformNode({
  id: "merge",
  inputSchema: FanInSchema,
  outputSchema: MergedSchema,
  transform: (fanIn) => ok({ analysis: fanIn.analyze.analysis, b: fanIn["fetch-b"].b }),
});

export const create${ctx.pascal}Dag = (opts: ${ctx.pascal}DagOpts = {}) =>
  ${helper}({
    id: "${ctx.name}",
    source: trigger,
    branches: [createAnalyze(opts.model ?? DEFAULT_MODEL), fetchB],
    join: merge,
  });

${registration(ctx, `create${ctx.pascal}Dag()`, `${kind} LLM scaffold for ${ctx.name}: an LLM branch + a deterministic branch, merged.`)}`;

  return {
    dagTs,
    prompt: {
      name: ctx.name,
      body: `You analyze a single item and report a short finding.

Analyze this item: {{label}}

Respond as JSON: { "analysis": string, "confidence": "high" | "medium" | "low" }.
Choose confidence by how strong the evidence is — never use a number.
`,
    },
  };
};

// ---------------------------------------------------------------------------
// router — classifier → cases + required default (defineRouter)
// ---------------------------------------------------------------------------

const router = (ctx: TemplateCtx): Scaffold => {
  if (!ctx.llm) {
    const dagTs = `// ${ctx.name} — conditional routing via \`defineRouter\`.
//
// A classifier feeds predicate-driven cases; the \`default\` branch is required
// at the type level, which eliminates the else-totality gaps raw \`defineDag\`
// would force you to hand-maintain. Generated by \`fugue new\`.

import { z } from "zod";
import {
  createFetchNode,
  createTransformNode,
  defineRouter,
  ok,
} from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

const InputSchema = z.object({ message: z.string() });
const IntentSchema = z.object({ category: z.enum(["billing", "support", "other"]) });
const ReplySchema = z.object({ reply: z.string() });

const classify = createFetchNode({
  id: "classify",
  inputSchema: InputSchema,
  outputSchema: IntentSchema,
  fetch: async (input) =>
    ok({ category: input.message.includes("invoice") ? "billing" : "other" }),
});

const handleBilling = createTransformNode({
  id: "handle-billing",
  inputSchema: IntentSchema,
  outputSchema: ReplySchema,
  transform: () => ok({ reply: "Routed to billing." }),
});

const handleSupport = createTransformNode({
  id: "handle-support",
  inputSchema: IntentSchema,
  outputSchema: ReplySchema,
  transform: () => ok({ reply: "Routed to support." }),
});

const handleOther = createTransformNode({
  id: "handle-other",
  inputSchema: IntentSchema,
  outputSchema: ReplySchema,
  transform: () => ok({ reply: "Routed to a human." }),
});

const dag = defineRouter({
  id: "${ctx.name}",
  classifier: classify,
  cases: {
    billing: {
      when: (out) => (out as z.infer<typeof IntentSchema>).category === "billing",
      to: handleBilling,
    },
    support: {
      when: (out) => (out as z.infer<typeof IntentSchema>).category === "support",
      to: handleSupport,
    },
  },
  default: handleOther, // REQUIRED
});

${registration(ctx, "dag", `Router scaffold for ${ctx.name}: classify a message, route to a handler, default to a human.`)}`;
    return { dagTs };
  }

  const dagTs = `// ${ctx.name} — conditional routing with an LLM CLASSIFIER, built as a FACTORY
// so the model seam is injectable. The \`default\` case is required at the type
// level. Generated by \`fugue new --llm\`.

import { z } from "zod";
import {
  confidence,
  createLlmNode,
  createTransformNode,
  defineRouter,
  ok,
} from "@fuguejs/framework";
import type { LlmNodeDef } from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

export interface ${ctx.pascal}DagOpts {
  /** Model seam; defaults to a current id. Tests pass a fake id + FakeLlmClient. */
  readonly model?: string;
}

const DEFAULT_MODEL = "${DEFAULT_MODEL}";

const InputSchema = z.object({ message: z.string() });
const IntentSchema = z.object({
  category: z.enum(["billing", "support", "other"]),
  confidence: z.enum(["high", "medium", "low"]),
});
const ReplySchema = z.object({ reply: z.string() });

const createClassify = (
  model: string,
): LlmNodeDef<z.infer<typeof InputSchema>, z.infer<typeof IntentSchema>> => {
  const node = createLlmNode({
    id: "classify",
    inputSchema: InputSchema,
    outputSchema: IntentSchema,
    promptName: "${ctx.name}",
    model,
    buildInput: (input) => ({ message: input.message }),
  });
${llmConfidenceReturn}
};

const handleBilling = createTransformNode({
  id: "handle-billing",
  inputSchema: IntentSchema,
  outputSchema: ReplySchema,
  transform: () => ok({ reply: "Routed to billing." }),
});

const handleSupport = createTransformNode({
  id: "handle-support",
  inputSchema: IntentSchema,
  outputSchema: ReplySchema,
  transform: () => ok({ reply: "Routed to support." }),
});

const handleOther = createTransformNode({
  id: "handle-other",
  inputSchema: IntentSchema,
  outputSchema: ReplySchema,
  transform: () => ok({ reply: "Routed to a human." }),
});

export const create${ctx.pascal}Dag = (opts: ${ctx.pascal}DagOpts = {}) =>
  defineRouter({
    id: "${ctx.name}",
    classifier: createClassify(opts.model ?? DEFAULT_MODEL),
    cases: {
      billing: {
        when: (out) => (out as z.infer<typeof IntentSchema>).category === "billing",
        to: handleBilling,
      },
      support: {
        when: (out) => (out as z.infer<typeof IntentSchema>).category === "support",
        to: handleSupport,
      },
    },
    default: handleOther, // REQUIRED
  });

${registration(ctx, `create${ctx.pascal}Dag()`, `Router LLM scaffold for ${ctx.name}: an LLM classifier routes a message to a handler.`)}`;

  return {
    dagTs,
    prompt: {
      name: ctx.name,
      body: `You classify an inbound message into one category.

Message: {{message}}

Respond as JSON:
{ "category": "billing" | "support" | "other", "confidence": "high" | "medium" | "low" }.
Pick confidence by how clear the message is — never use a number.
`,
    },
  };
};

// ---------------------------------------------------------------------------
// sources — N parallel SOURCE nodes → keyed join → assemble (defineSources)
// ---------------------------------------------------------------------------

const sources = (ctx: TemplateCtx): Scaffold => {
  if (!ctx.llm) {
    const dagTs = `// ${ctx.name} — multi-source join (N parallel sources → keyed fan-in → assemble)
// via \`defineSources\`. The most common real topology. Generated by \`fugue new\`.
//
// Durable bits worth keeping:
//   * roots are SOURCE nodes (\`createSourceNode\`, no \`inputSchema\`) — a source
//     produces from the context alone and consumes no DAG input;
//   * the join's fan-in keys are EXACTLY the source node ids (\`fugue lint\` checks);
//   * the request reaches \`assemble\` via a \`$input\` edge, declared as the
//     "$input" key in its fan-in. \`defineSources\` wires that edge automatically.

import { z } from "zod";
import {
  createSourceNode,
  createTransformNode,
  defineSources,
  ok,
} from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

const InputSchema = z.object({ region: z.string() });

const ASchema = z.object({ a: z.string() });
const fetchA = createSourceNode({
  id: "fetch-a",
  outputSchema: ASchema,
  fetch: async () => ok({ a: "alpha" }),
});

const BSchema = z.object({ b: z.number() });
const fetchB = createSourceNode({
  id: "fetch-b",
  outputSchema: BSchema,
  fetch: async () => ok({ b: 1 }),
});

const CSchema = z.object({ c: z.boolean() });
const fetchC = createSourceNode({
  id: "fetch-c",
  outputSchema: CSchema,
  fetch: async () => ok({ c: true }),
});

// Join: fan-in keyed by the THREE source node ids.
const JoinFanIn = z.object({
  "fetch-a": ASchema,
  "fetch-b": BSchema,
  "fetch-c": CSchema,
});
const JoinedSchema = z.object({ a: z.string(), b: z.number(), c: z.boolean() });

const join = createTransformNode({
  id: "join",
  inputSchema: JoinFanIn,
  outputSchema: JoinedSchema,
  transform: (fanIn) =>
    ok({ a: fanIn["fetch-a"].a, b: fanIn["fetch-b"].b, c: fanIn["fetch-c"].c }),
});

// Assemble: fan-in over the join + the request via the "$input" slot. Declaring
// "$input" here is what makes \`defineSources\` add the DAG_INPUT edge.
const AssembleFanIn = z.object({
  join: JoinedSchema,
  $input: InputSchema,
});
const ResultSchema = z.object({ region: z.string(), a: z.string(), b: z.number() });

const assemble = createTransformNode({
  id: "assemble",
  inputSchema: AssembleFanIn,
  outputSchema: ResultSchema,
  transform: (input) =>
    ok({ region: input.$input.region, a: input.join.a, b: input.join.b }),
});

const dag = defineSources({
  id: "${ctx.name}",
  sources: [fetchA, fetchB, fetchC],
  join,
  assemble,
});

${registration(ctx, "dag", `Multi-source join scaffold for ${ctx.name}: parallel sources → keyed join → assemble (request via $input).`)}`;
    return { dagTs };
  }

  const dagTs = `// ${ctx.name} — multi-source join where the JOIN is an LLM node, built as a
// FACTORY so the model seam is injectable. Sources → LLM join → assemble, via
// \`defineSources\`. Generated by \`fugue new --llm\`.
//
// The join consumes the fan-in of source outputs (keys = source node ids) and
// returns bucketed confidence. The request reaches \`assemble\` via a \`$input\`
// edge (the "$input" key in its fan-in).

import { z } from "zod";
import {
  confidence,
  createLlmNode,
  createSourceNode,
  createTransformNode,
  defineSources,
  ok,
} from "@fuguejs/framework";
import type { LlmNodeDef } from "@fuguejs/framework";
import type { DagRegistration } from "@fuguejs/host/contract";

export interface ${ctx.pascal}DagOpts {
  /** Model seam; defaults to a current id. Tests pass a fake id + FakeLlmClient. */
  readonly model?: string;
}

const DEFAULT_MODEL = "${DEFAULT_MODEL}";

const InputSchema = z.object({ region: z.string() });

const ASchema = z.object({ a: z.string() });
const fetchA = createSourceNode({
  id: "fetch-a",
  outputSchema: ASchema,
  fetch: async () => ok({ a: "alpha" }),
});

const BSchema = z.object({ b: z.string() });
const fetchB = createSourceNode({
  id: "fetch-b",
  outputSchema: BSchema,
  fetch: async () => ok({ b: "beta" }),
});

// Join: an LLM node whose fan-in keys are EXACTLY the source node ids.
const JoinFanIn = z.object({
  "fetch-a": ASchema,
  "fetch-b": BSchema,
});
const SynthSchema = z.object({
  summary: z.string(),
  confidence: z.enum(["high", "medium", "low"]),
});

const createSynthesize = (
  model: string,
): LlmNodeDef<z.infer<typeof JoinFanIn>, z.infer<typeof SynthSchema>> => {
  const node = createLlmNode({
    id: "synthesize",
    inputSchema: JoinFanIn,
    outputSchema: SynthSchema,
    promptName: "${ctx.name}",
    model,
    buildInput: (fanIn) => ({ a: fanIn["fetch-a"].a, b: fanIn["fetch-b"].b }),
  });
${llmConfidenceReturn}
};

// Assemble: fan-in over the LLM join + the request via the "$input" slot.
const AssembleFanIn = z.object({
  synthesize: SynthSchema,
  $input: InputSchema,
});
const ResultSchema = z.object({ region: z.string(), summary: z.string() });

const assemble = createTransformNode({
  id: "assemble",
  inputSchema: AssembleFanIn,
  outputSchema: ResultSchema,
  transform: (input) =>
    ok({ region: input.$input.region, summary: input.synthesize.summary }),
});

export const create${ctx.pascal}Dag = (opts: ${ctx.pascal}DagOpts = {}) =>
  defineSources({
    id: "${ctx.name}",
    sources: [fetchA, fetchB],
    join: createSynthesize(opts.model ?? DEFAULT_MODEL),
    assemble,
  });

${registration(ctx, `create${ctx.pascal}Dag()`, `Multi-source LLM join scaffold for ${ctx.name}: parallel sources → LLM synthesis → assemble.`)}`;

  return {
    dagTs,
    prompt: {
      name: ctx.name,
      body: `You synthesize a short summary from two source facts.

Source A: {{a}}
Source B: {{b}}

Respond as JSON: { "summary": string, "confidence": "high" | "medium" | "low" }.
Choose confidence by how consistent the sources are — never use a number.
`,
    },
  };
};

/** Build the `dag.ts` (and prompt, for `--llm`) for a shape. Pure. */
export const buildScaffold = (shape: Shape, ctx: TemplateCtx): Scaffold =>
  match(shape)
    .with("linear", () => linear(ctx))
    .with("fan-out", () => fanShape(ctx, "defineFanOut"))
    .with("diamond", () => fanShape(ctx, "defineDiamond"))
    .with("router", () => router(ctx))
    .with("sources", () => sources(ctx))
    .exhaustive();

// A plain (unquoted) YAML scalar is only safe for a conservative shape: it must
// start alphanumeric and contain no character that changes YAML meaning (`:`,
// `#`, newlines, leading/trailing space, indicators). `team` is path-derived and
// kebab-constrained so it is always safe; `owner` is freeform author input.
const SAFE_YAML_SCALAR = /^[A-Za-z0-9][\w .@+-]*$/;

/**
 * Render a string as a YAML scalar that round-trips to the original value.
 * Safe values stay plain (`owner: peter.hansen`); anything else is emitted as a
 * double-quoted scalar via `JSON.stringify` — JSON's escape grammar is a subset
 * of YAML's double-quoted grammar, so `owner: foo: bar` / a newline / a leading
 * `#` produce valid `fugue.yaml` by construction instead of malformed output.
 */
const yamlScalar = (value: string): string =>
  SAFE_YAML_SCALAR.test(value) && !value.endsWith(" ") ? value : JSON.stringify(value);

/** `fugue.yaml` — team from the `<team>/<name>` path; owner optional. */
export const fugueYaml = (ctx: TemplateCtx, owner?: string): string =>
  owner !== undefined
    ? `team: ${ctx.team}\nowner: ${yamlScalar(owner)}\n`
    : `team: ${ctx.team}\n# owner: your.name   # optional — individual owner within the team\n`;

/** Per-DAG README stub: what it does, route, and the verification loop. */
export const readme = (ctx: TemplateCtx, shape: Shape): string =>
  `# ${ctx.name}

> Scaffolded by \`fugue new ${ctx.team}/${ctx.name} --shape ${shape}${ctx.llm ? " --llm" : ""}\`.
> Replace this description, the placeholder schemas, and the node bodies.

**Team:** ${ctx.team}
**Route:** \`/${ctx.name}\`
**Shape:** ${shape}${ctx.llm ? " (LLM)" : ""}

## What it does

TODO — describe the request, the sources/steps, and the response.

## Verify

\`\`\`bash
bun node_modules/@fuguejs/framework/bin/fugue.ts lint     dags/${ctx.team}/${ctx.name}/dag.ts
bun node_modules/@fuguejs/framework/bin/fugue.ts describe  dags/${ctx.team}/${ctx.name}/dag.ts
${ctx.llm ? `bun node_modules/@fuguejs/framework/bin/fugue.ts prompts check dags/${ctx.team}/${ctx.name}\n` : ""}bun test
\`\`\`
`;
