// token-usage — the framework's single vocabulary for LLM token consumption.
//
// Functional core: pure values and pure functions, no I/O, no clocks. Lives in
// `types/` (not `llm/`) because `types/errors.ts` and `types/llm.ts` both need
// it, and `types/**` must not import from `llm/**` (the same cycle-avoidance
// that moved the LLM-facing public types here — see `types/llm.ts` header).
//
// WHY A VALUE TYPE AND NOT FOUR LOOSE NUMBERS: before prompt caching the token
// figures travelled as a `{ tokensIn, tokensOut }` pair through fourteen
// non-test modules — both clients' success and error arms, the tool-use loop's
// cross-turn accumulator, span enrichment, the MLflow exporter, the eval-judge
// node, the host's meter and its metering log. Widening that pair in place
// would have multiplied the places a field can be silently forgotten. The
// concept now has one owner: construct through the smart constructors below,
// combine through `addUsage`, and derive everything else.

/**
 * Tokens consumed by one LLM call (or, after `addUsage`, by a run of them).
 *
 * `tokensIn` is the COMPLETE prompt count — uncached input plus cache-write
 * plus cache-read — normalised across providers by the clients:
 *
 * - Anthropic reports `usage.input_tokens` as the UNCACHED REMAINDER, with
 *   `cache_creation_input_tokens` / `cache_read_input_tokens` alongside; the
 *   client sums all three (`anthropicUsage`).
 * - OpenAI reports `usage.input_tokens` INCLUSIVE of cached tokens, which are
 *   broken out under `input_tokens_details.cached_tokens`; the client passes
 *   the total through unchanged (`openAiUsage`).
 *
 * Keeping `tokensIn` inclusive is what lets the host's per-run budget
 * (`runTotal = tokensIn + tokensOut`) stay correct when a cache policy is
 * enabled: without it, `input_tokens` would silently shrink to the uncached
 * remainder and every budget would under-count with no error raised.
 *
 * The uncached remainder is DERIVED (`uncachedInputTokens`), never stored —
 * the same discipline the host meter applies to its cumulative total, and for
 * the same reason: storing a total beside its parts makes `total !== sum(parts)`
 * representable, and that value feeds a budget decision.
 *
 * @satisfies FR-PC-005 — `tokensIn` counts every prompt token, every provider
 */
export interface TokenUsage {
  /** ALL prompt tokens: uncached + cache-write + cache-read. */
  readonly tokensIn: number;
  /** Tokens generated by the model. */
  readonly tokensOut: number;
  /**
   * Prompt tokens written to a NEW provider-side cache entry by this call,
   * billed at the write premium (1.25x at a 5m TTL, 2x at 1h). Zero when no
   * cache policy is active, when the prefix is below the model's minimum
   * cacheable size, or when the provider offers no request-side cache control.
   */
  readonly cacheWriteTokens: number;
  /**
   * Prompt tokens served from an EXISTING provider-side cache entry, billed at
   * roughly 0.1x the base input rate.
   */
  readonly cacheReadTokens: number;
}

/**
 * Coerce one provider-reported count into a usable non-negative finite number.
 *
 * A provider count is untrusted JSON even when the SDK types say `number`: a
 * negative figure would read as a token refund, and a non-finite one would
 * poison every later sum (`NaN` propagates, and `NaN >= budget` is false
 * forever, so a budget would fail OPEN). Both read as "no attributable tokens".
 *
 * Every `TokenUsage` producer routes through this, so the invariant holds at
 * CONSTRUCTION rather than being re-defended by each downstream consumer.
 */
export const sanitizeCount = (n: number): number =>
  Number.isFinite(n) ? Math.max(0, n) : 0;

/** The additive identity — a call that consumed nothing. */
export const NO_TOKENS: TokenUsage = Object.freeze({
  tokensIn: 0,
  tokensOut: 0,
  cacheWriteTokens: 0,
  cacheReadTokens: 0,
});

/**
 * Smart constructor for the no-caching case: a call whose entire prompt was
 * billed at the base input rate. Keeps the ~60 existing two-number
 * construction sites honest without spreading `cacheWriteTokens: 0,
 * cacheReadTokens: 0` across all of them.
 *
 * Sanitizes, like every other producer in this module. It is the constructor
 * MOST call sites use, so it opting out would have made this module's
 * construction-time guarantee false where it matters most: a malformed
 * provider count would reach the host's structured metering log verbatim (the
 * budget itself re-sanitizes at the `Spend` boundary, so the figure never
 * reached a decision — but "the invariant holds at construction" has to be
 * true of the constructor, not merely of the consumer).
 */
export const tokensOnly = (tokensIn: number, tokensOut: number): TokenUsage => ({
  tokensIn: sanitizeCount(tokensIn),
  tokensOut: sanitizeCount(tokensOut),
  cacheWriteTokens: 0,
  cacheReadTokens: 0,
});

/**
 * Narrow a value that CARRIES usage down to exactly its usage.
 *
 * `LlmResponse extends TokenUsage`, so a response is structurally a valid
 * `TokenUsage` and can be passed wherever one is expected — but it also carries
 * `output`, `thinking`, and `rawText`. A consumer that SPREADS what it was
 * handed therefore spreads model output and chain-of-thought too, which is how
 * generated content reaches places that were only ever meant to see numbers
 * (a metering log line, a metrics label, a persisted counter).
 *
 * Note the deliberate inversion of the advice in this module's header: fields
 * are listed rather than spread precisely because the goal here is to EXCLUDE
 * everything else, which spreading cannot do. Completeness stays
 * compiler-enforced in both directions by the return annotation — a field
 * dropped from the literal fails to satisfy `TokenUsage`, and a field added to
 * `TokenUsage` fails for the same reason.
 */
export const pickUsage = ({
  tokensIn,
  tokensOut,
  cacheWriteTokens,
  cacheReadTokens,
}: TokenUsage): TokenUsage => ({
  tokensIn,
  tokensOut,
  cacheWriteTokens,
  cacheReadTokens,
});

/**
 * Monoid append over `NO_TOKENS`. The tool-use loop folds one of these per
 * turn to produce the call's cross-turn total (FR-PC-007); the host meter
 * folds one per call to produce the run total.
 *
 * @satisfies FR-PC-007 — cross-turn accumulation of cache figures
 */
export const addUsage = (a: TokenUsage, b: TokenUsage): TokenUsage => ({
  tokensIn: a.tokensIn + b.tokensIn,
  tokensOut: a.tokensOut + b.tokensOut,
  cacheWriteTokens: a.cacheWriteTokens + b.cacheWriteTokens,
  cacheReadTokens: a.cacheReadTokens + b.cacheReadTokens,
});

/**
 * Prompt tokens billed at the FULL base input rate — derived, never stored.
 *
 * Clamped at zero so a provider that ever reports a cache breakdown exceeding
 * its own inclusive total cannot produce a negative charge downstream in
 * `computeCostUsd`. A clamp fires only on provider self-inconsistency; the
 * normal path is exact.
 */
export const uncachedInputTokens = (u: TokenUsage): number =>
  Math.max(0, u.tokensIn - u.cacheWriteTokens - u.cacheReadTokens);

/** Every token that crossed the wire, in either direction. */
export const totalTokens = (u: TokenUsage): number => u.tokensIn + u.tokensOut;

/**
 * Share of the prompt served from the provider-side cache, in `[0, 1]`.
 * Zero prompt tokens yields `0` — an empty prompt has no hit rate to report.
 */
export const cacheHitRatio = (u: TokenUsage): number =>
  u.tokensIn <= 0 ? 0 : Math.min(1, u.cacheReadTokens / u.tokensIn);

/**
 * True when this call neither wrote nor read a provider-side cache entry.
 *
 * A call whose request DECLARED a cache policy and comes back inert is the
 * silent-failure case prompt caching invites: the provider caches nothing and
 * raises nothing when the prefix sits below the model's minimum cacheable size
 * (512-4096 tokens, model-dependent) or when a volatile byte sits inside the
 * prefix. Callers pair this with the request's policy to warn (FR-PC-009).
 */
export const isCacheInert = (u: TokenUsage): boolean =>
  u.cacheWriteTokens === 0 && u.cacheReadTokens === 0;
