// llm-pipeline — shared LLM call pipeline (cache → call → validate+retry → enrich → cache-write).
//
// Deep module: callers learn one function; the pipeline hides cache error
// handling, validation retry (FR-021), span enrichment, and cache-write
// best-effort semantics behind a single invocation.
//
// The call strategy seam (`callFn`) is a function parameter — `sendStructured`
// and `sendWithTools` have different request shapes; the pipeline doesn't care
// which. It passes the resolved prompts and receives a Result<LlmResponse>.

import type { z } from "zod";
import type { FrameworkError } from "../types/errors.js";
import type { NodeId } from "../types/ids.js";
import type { ConversationCachePolicy, LlmResponse } from "../types/llm.js";
import { isCacheInert } from "../types/token-usage.js";
import { cachePolicyLabel, planPromptCache } from "../llm/prompt-cache.js";
import type { NodeContext } from "../types/node.js";
import { type Result, ok, err } from "../types/result.js";
import { enrichLlmSpan } from "../tracing/index.js";
import { formatFrameworkError } from "../types/errors.js";

export interface LlmPipelineConfig<O> {
  readonly nodeId: NodeId;
  readonly model: string;
  readonly outputSchema: z.ZodType<O>;
  readonly prompts: { readonly system: string; readonly user: string };
  readonly cacheKey: string;
  readonly disableValidationRetry?: boolean;
  readonly promptName?: string;
  /**
   * Fingerprint of the PROMPT SOURCES (system prompt + user template — not
   * the interpolated message). Appended to `cacheKey` so editing a prompt
   * invalidates cached outputs, and stamped on the LLM span
   * (`ai.prompt_hash`) so traces identify which prompt version produced an
   * output. Without it, a custom `computeCacheKey` keeps serving outputs
   * generated by an OLD prompt until the cache TTL expires.
   */
  readonly promptFingerprint?: string;
  readonly thinking?: { type: "enabled"; budgetTokens: number };
  /**
   * The prompt-cache policy the node declared, threaded here so the pipeline
   * can stamp it on the span and detect an INERT policy — one that asked the
   * provider to cache and got neither a write nor a read back. Omitted ≡ no
   * policy declared.
   */
  readonly cache?: ConversationCachePolicy;
}

/**
 * The call-strategy seam. Invoked with no arguments beyond what the pipeline
 * already supplies (client access, prompts, ctx are closed over by the caller).
 * Returns a `Result<LlmResponse<O>, FrameworkError>`.
 */
export type LlmCallFn<O> = () => Promise<Result<LlmResponse<O>, FrameworkError>>;

/**
 * Shared pipeline: cache-read → call → validate+retry → enrich → cache-write.
 *
 * Both `createLlmNode` and `createLlmWithToolsNode` delegate here after
 * resolving prompts and constructing the call function. The pipeline owns:
 *
 * - Cache lookup (opt-in, best-effort on read failure)
 * - LLM call via the injected `callFn`
 * - Output schema validation + FR-021 single-shot retry
 * - GenAI semconv span enrichment
 * - Cache write (best-effort, failures never break a successful run)
 */
export const runLlmCallPipeline = async <O>(
  config: LlmPipelineConfig<O>,
  callFn: LlmCallFn<O>,
  ctx: NodeContext,
): Promise<Result<O, FrameworkError>> => {
  // The effective key binds the caller's key to the prompt version: an edited
  // prompt must never serve outputs generated by its predecessor.
  const cacheKey = config.promptFingerprint !== undefined
    ? `${config.cacheKey}:pf:${config.promptFingerprint}`
    : config.cacheKey;

  // 1. Cache read (opt-in — cache may be null)
  if (ctx.cache) {
    try {
      const lookup = await ctx.cache.get(cacheKey);
      if (lookup.hit) {
        const parsed = config.outputSchema.safeParse(lookup.value);
        if (parsed.success) return ok(parsed.data);
        ctx.logger.warn(
          `[${config.nodeId}] Cache hit failed schema validation, treating as miss`,
        );
      }
    } catch (e) {
      ctx.logger.warn(
        `[${config.nodeId}] Cache read failed (cacheKey=${cacheKey}): ${e instanceof Error ? e.message : e}`,
      );
    }
  }

  // 2. LLM call + output validation
  const attempt = async (): Promise<Result<LlmResponse<O>, FrameworkError>> => {
    const result = await callFn();
    if (!result.ok) return result;

    const parsed = config.outputSchema.safeParse(result.value.output);
    if (!parsed.success) {
      return err({
        kind: "validation" as const,
        nodeId: config.nodeId,
        message: `LLM output validation failed: ${parsed.error.message}`,
      });
    }
    return ok(result.value);
  };

  let result = await attempt();

  // 3. FR-021: retry once on validation failure
  if (!result.ok && result.error.kind === "validation" && !config.disableValidationRetry) {
    result = await attempt();
    if (!result.ok) {
      return err({
        kind: "retry-exhausted" as const,
        nodeId: config.nodeId,
        attempts: 2,
        lastError: formatFrameworkError(result.error),
        rootErrorKind:
          result.error.kind === "retry-exhausted"
            ? result.error.rootErrorKind
            : result.error.kind,
      });
    }
  }

  if (!result.ok) return result;

  const llmResponse = result.value;

  // 4. Span enrichment
  const cachePolicy = cachePolicyLabel(config.cache);
  // The TTL comes from the plan rather than from an `in` check on the policy —
  // `prompt-cache.ts` owns the policy-to-placement mapping, and re-deriving it
  // here is how the two would drift.
  const cacheWriteTtl = planPromptCache(config.cache).ttl ?? undefined;
  enrichLlmSpan({
    model: config.model,
    promptName: config.promptName,
    promptHash: config.promptFingerprint,
    system: config.prompts.system,
    user: config.prompts.user,
    usage: llmResponse,
    cachePolicy,
    ...(cacheWriteTtl ? { cacheWriteTtl } : {}),
    thinking: llmResponse.thinking,
    contentFilter: ctx.contentFilter,
  });

  // 4b. A declared cache policy that neither wrote nor read an entry did
  // NOTHING, and the provider says so by omission: it caches nothing and
  // raises nothing when the prefix sits below the model's minimum cacheable
  // size (512-4096 tokens, model-dependent) or when a volatile byte broke the
  // prefix match. Announcing it is the difference between "caching is on" and
  // "caching is working" — the same silent-success rule the framework applies
  // to dropped checkpoint entries.
  if (cachePolicy !== "none" && isCacheInert(llmResponse)) {
    ctx.logger.warn(
      `[${config.nodeId}] Prompt cache policy "${cachePolicy}" was declared but the provider ` +
        `reported no cache write and no cache read (${llmResponse.tokensIn} prompt tokens). ` +
        `Likely causes: the cacheable prefix is below this model's minimum, or content before ` +
        `the breakpoint changes between calls.`,
    );
  }

  const output = llmResponse.output as O;

  // 5. Cache write (best-effort — failures must never break a successful run).
  // No per-call TTL: expiry policy belongs to the adapter (the host wires the
  // per-DAG cacheTtlMs / host default into it). A hardcoded TTL here silently
  // overrode every DAG's configured cacheTtlMs — see ContextCacheAdapter.set.
  if (ctx.cache) {
    try {
      const setResult = await ctx.cache.set(cacheKey, output);
      if (!setResult.ok) {
        ctx.logger.warn(
          `[${config.nodeId}] Cache write failed: ${setResult.error.kind === "cache-error" ? setResult.error.message : String(setResult.error)}`,
        );
      }
    } catch (e) {
      ctx.logger.warn(
        `[${config.nodeId}] Cache write threw: ${e instanceof Error ? e.message : e}`,
      );
    }
  }

  return ok(output);
};
